// Generated by CoffeeScript 1.6.3
(function() {
  var favicon, isTarget, notico;

  favicon = null;

  isTarget = true;

  window.onload = function() {
    var config, observer, target;
    try {
      favicon = new Favico({
        animation: 'fade',
        noticofication: 'jump',
        bgColor: '#0d0'
      });
      favicon.badge(0);
      target = document.getElementsByTagName('title')[0];
      config = {
        subtree: true,
        characterData: true,
        childList: true
      };
      observer = new WebKitMutationObserver(function(mutations) {
        if (isTarget) {
          return notico.changeTitle(mutations);
        }
      });
      return observer.observe(target, config);
    } catch (_error) {}
  };

  notico = {};

  notico.isDisplayedBadge = false;

  notico.changeTitle = function(mutations) {
    var badgeNum, title;
    if (mutations.length > 0) {
      if (!mutations) {
        isTarget = false;
        return;
      }
      title = mutations[0].target.data;
      badgeNum = notico.badgeNum(title);
      console.log(badgeNum);
      if (badgeNum < 1) {
        notico.resetBadge();
        return;
      }
      return notico.displayBadge(badgeNum);
    }
  };

  notico.badgeNum = function(str) {
    var m;
    m = str.match(/^\(([0-9]+)\)/);
    if (m) {
      return Number(m[1]);
    }
    return -1;
  };

  notico.displayBadge = function(num) {
    try {
      return favicon.badge(num);
    } catch (_error) {
      return isTarget = false;
    }
  };

  notico.resetBadge = function() {
    return favicon.reset();
  };

}).call(this);
